removed forced deploy failure

diff --git a/.github/workflows/cd-01.yml b/.github/workflows/cd-01.yml
--- a/.github/workflows/cd-01.yml
+++ b/.github/workflows/cd-01.yml
@@ -62,13 +62,13 @@ jobs:
         run: |
           mkdir -p ~/.kube
           echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
-      # - name: Deploy
-      #   run: |
-      #     helm upgrade devops-app ./chart \
-      #       --install --atomic --timeout 5m \
-      #       --namespace prod \
-      #       --set image.tag=${{ github.sha }}
       - name: Deploy
         run: |
-          echo "Simulating failure"
-          exit 1
+          helm upgrade devops-app ./chart \
+            --install --atomic --timeout 5m \
+            --namespace prod \
+            --set image.tag=${{ github.sha }}
+      # - name: Deploy
+      #   run: |
+      #     echo "Simulating failure"
+      #     exit 1
